### ISSUE TITLE
Android incorrect image crop

### ISSUE THREAD

**Issue by YUstynov** [HarvestProfit/react-native-rectangle-scanner#14] opened 2020-02-03 09:55 UTC
Hi, module detects rectangle, adds border and background color successfully, but after image capture it returns cropped top left part of image with width and height of detected rectangle. It always start to crop from 0,0  in my case. Seems that submat(0, height, 0, width) from openCV works incorrect. I took code from example folder

**Comment by humphreyja** [comment] 2020-02-03 17:09
Hmmm interesting. What phone and android version is this on?

**Comment by YUstynov** [comment] 2020-02-04 09:29
Im using samsung galaxy m30s, Android 9

**Comment by humphreyja** [comment] 2020-02-04 23:59
@YUstynov How much experience do you have with working with Android/Java? Would you be able to debug this on your machine as I haven't seen this error on any emulator. Here's some stuff to try if you have the knowledge.

I suspect that maybe the preview and the final output image have different dimensions. In the [ImageProcessor](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/helpers/ImageProcessor.java) file, can you check the function `cropImageToLatestQuadrilateral` for the `this.lastDetectedRectangle` size and the `inputRgba` size. They should line up. 

Otherwise, digging deeper the issue would be in the `fourPointTransform` function which is where the cropping happens. The dimensions might be off somehow.

**Comment by adrianocola** [comment] 2020-02-05 11:47
I'm experiencing the same issue. I debugged the function `imageProcessor` and the `inputRgba` size is 3024 x 4032 (the resolution of pictures taken with my phone) while `this.lastDetectedRectangle` size is 1080x1920 (the resolution of my phone screen).

 I'm testing on a real device, Samsung Galaxy S7 Edge

**Comment by humphreyja** [comment] 2020-02-05 19:36
@adrianocola Ok perfect, that makes perfect sense why this isn't working right. Android is a bit odd because the preview and captured image resolutions and sizes are preset. The immediate fix for this will be to add the ratio and scale to the detected rectangle so that it scales with the captured image. I should have time to work on this tonight.

I'll note this here so anyone else who runs into similar issues will have some context. There can still be a potential bug if the preview and the captured image ratios are different. The point of [CameraDeviceController.getOptimalResolution](https://github.com/HarvestProfit/react-native-rectangle-scanner/blob/master/android/src/main/java/com/rectanglescanner/views/CameraDeviceController.java#L239) is to try to match the resolution ratios the best it can but it is still device specific and may run into issues on some devices. **I've tried it on a lot of devices, even an old LG G3 haha, and they all had matching ratio presets so maybe this won't be an issue**

**Comment by humphreyja** [comment] 2020-02-06 06:08
@adrianocola, @YUstynov I was able to reproduce the issue in an emulator and got a fix out for this with PR #15. Could you verify if that works for you?

**Comment by YUstynov** [comment] 2020-02-06 12:30
Unfortunately still doesn't work. I have best results in portrait mode. Image correctly cropped horizontal, but not vertical. Top is cropped image, bottom is original.
![1580991388151](https://user-images.githubusercontent.com/42536222/73937145-167d9780-48ed-11ea-94a8-8fd8fb9052ea.JPEG)

**Comment by adrianocola** [comment] 2020-02-06 15:07
@humphreyja I also had the same results as @YUstynov, but I think that this is happening because of different aspect ratios (my camera highest resolution image is 4:3 and my display is 16:9). I changed the method `CameraDeviceController.getOptimalResolution` to only consider aspect ratios matching my display:

```java
private Camera.Size getOptimalResolution(float ratioToFitTo, List<Camera.Size> resolutionList) {
        int maxPixels = 0;
        int ratioMaxPixels = 0;
        Camera.Size currentMaxRes = null;
        Camera.Size ratioCurrentMaxRes = null;
        for (Camera.Size r : resolutionList) {
            float pictureRatio = (float) r.width / r.height;
            Log.d(TAG, "supported resolution: " + r.width + "x" + r.height + " ratio: " + pictureRatio + " ratioToFitTo: " + ratioToFitTo);
            int resolutionPixels = r.width * r.height;
            if (resolutionPixels > ratioMaxPixels && ratioToFitTo == pictureRatio) {
                ratioMaxPixels = resolutionPixels;
                ratioCurrentMaxRes = r;
            }

            if (resolutionPixels > maxPixels && ratioToFitTo == pictureRatio) {
                maxPixels = resolutionPixels;
                currentMaxRes = r;
            }
        }

        if (ratioCurrentMaxRes != null) {

            Log.d(TAG, "Max supported resolution with aspect ratio: " + ratioCurrentMaxRes.width + "x"
                    + ratioCurrentMaxRes.height);
            return ratioCurrentMaxRes;

        }

        return currentMaxRes;
    }
```

**Comment by humphreyja** [comment] 2020-02-06 18:38
Hmm ok thanks for the feedback. I think the best solution may be to crop the output photo to the size of the preview before cropping the rectangle. That way this will work for phones that may not have a matching preview and captured photo (regardless if the `getOptimalResolution` function is buggy).

@adrianocola So `getOptimalResolution` is returning different ratio sizes instead of returning the best fitting ratio size? Guess it's time to figure out how to add some tests to this as this is one of the more important functions for android. The idea behind the `bestRatioDifference` was to allow some margin of error if the preview and captured ratios don't match, so I don't know if it's the best idea to remove that, but it should be tested and maybe reduced. 

For example, I've found a few instances where android doesn't have a matching preview resolution that matches the display size, that is why I send the height and width % to the `onDeviceSetup` so the react component can add some margin so the preview image is not skewed. You'll notice all the other android/reactnative scanner packages have this issue.

**Comment by humphreyja** [comment] 2020-02-06 18:40
Sorry for the wall of comments haha but @YUstynov, for the original image, is it being outputted in that rotated state?

**Comment by YUstynov** [comment] 2020-02-07 08:51
Yeah, i took uri from

`  onPictureProcessed = (event) => {
    this.setState({
      originImage: event.initialImage
    })}`

and display it in in react-native image component... Styles are for width and height only.

`  <Image source={{uri: this.state.originImage}}
                   resizeMode="contain"
                   style={styles.processedImage}/>`

**Comment by YUstynov** [comment] 2020-02-10 13:27
Did this
`scaledPoints[i].y *= scale;`
`scaledPoints[i].x += 180;`
`scaledPoints[i].x *= scale;`
Don't know what is that magic number 180 and how to calculate it without hardcode but... it works. Tested on 4 different real android devices

**Comment by humphreyja** [comment] 2020-02-11 22:17
@adrianocola @YUstynov I just updated that PR to include a step that will crop the captured image to the aspect ratio of the detected rectangle. That way it will always have the same aspect ratio as the detected rectangle image. I think that that "180" value comes from the difference between the preview and captured image resolution sizes. Could you verify if that fixes this problem on your side?

**Comment by YUstynov** [comment] 2020-02-13 11:21
Thank a lot. It fixes the problem.

**Comment by humphreyja** [comment] 2020-02-13 17:25
Awesome, thanks for all the help everyone. I'll get this merged in and get a new release out before the weekend.

**Closed** 2020-02-14 16:04 UTC
Labels: android, bug
